WIP [TS-215] app is optional + additional commands
cryptopay-dev/yaga pull request #56
Opened 2018-02-20 14:55 UTC by jenchik

2018-02-20 15:24 UTC, im-kulikov commented on cli/interface.go
> +	Commandor func(*Options) Command
funny

2018-02-21 15:02 UTC, im-kulikov commented on cli/options.go
> +		o.commands = make([]Command, 0, len(cmds))
every time rewrite?

2018-02-21 15:07 UTC, jenchik commented on cli/options.go
> +		o.commands = make([]Command, 0, len(cmds))
I think so, it's better

2018-02-22 09:45 UTC, pcherednichenko commented
посмотрел, в целом все ок
поскольку *WIP* смотрел чисто в общем

2018-02-22 13:33 UTC, im-kulikov commented on cli/cli.go
> +		if err = validator.New().Struct(options); err != nil {
`return validator.New().Struct(options)`

2018-02-22 13:33 UTC, im-kulikov commented on cli/cli.go
> +	if opts.DB, err = dbConf.Connect(); err != nil {
```go
/...

opts.DB, err = dbConf.Connect()
return err
```

2018-02-26 10:03 UTC, im-kulikov requested changes
```sh
→ ./builder init --dir ../something2
Project mame: something2
Project full name: thub.com/cryptopay-dev/something2
Project path: /Users/kulikov/.golang/src/github.com/cryptopay-dev/something2
panic: exit status 1

goroutine 1 [running]:
main.main()
        /Users/kulikov/.golang/src/github.com/cryptopay-dev/yaga/cmd/main.go:100 +0x2ca

```

2018-02-26 11:08 UTC, im-kulikov commented on cmd/project_example/app/app.go
> +	Debug        bool
remove:
- Debug
- BuildTime
- BuildVersion

2018-02-26 11:29 UTC, im-kulikov submitted a review, later dismissed
I do not quite agree with the use of
- `vars`
- `cp`

but as a first iteration.. I guess it's ok

2018-02-26 12:39 UTC, im-kulikov commented on cmd/project_example/app/library/config/config.go
> +	Bind string `yaml:"bind" validate:"required"`
pls add:

```go
// Database    config.Database `yaml:"database" validate:"required,dive"`
// Redis    config.Redis `yaml:"redis" validate:"required,dive"`
```

2018-02-26 12:42 UTC, im-kulikov commented on cmd/project_example/config.example.yml
> +bind: :8080
pls add:

```yaml
# example database:
#database:
#  address: localhost:5432
#  database: dillinger
#  user: postgres
#  password: postgres

# example redis:
#redis:
#  address: 127.0.0.1:6379
#  database: 0
#  password:
#  pool_size: 10
#  pool_timeout: 3
```

2018-02-26 12:55 UTC, im-kulikov commented
XD `vars/vars.go` + `misc/vars.go`... more... add more!

2018-02-26 12:56 UTC, pcherednichenko submitted a review, later dismissed

2018-02-26 12:59 UTC, im-kulikov commented on cmd/project_example/Gopkg.toml
> +  name = "gopkg.in/go-playground/validator.v9"
for what?... it is already in the Yaga :)

2018-02-26 13:05 UTC, im-kulikov commented on cmd/project_example/Gopkg.toml
> +  name = "gopkg.in/go-playground/validator.v9"
https://github.com/cryptopay-dev/yaga/blob/bce5c14b703b19912163d4335d6cd571be9834bf/Gopkg.lock#L238-L242

2018-02-26 13:08 UTC, im-kulikov approved these changes
![giphy-0](https://user-images.githubusercontent.com/888650/36672160-51e682ea-1b0f-11e8-890c-3cfe371a40f6.gif)

2018-02-26 13:11 UTC, pcherednichenko approved these changes

2018-02-26 13:14 UTC, merged